version: '3'

services:
  rustla2:
    build: ./
    image: rustla2:stable
    volumes:
      - ..:/Rustla2:rw
    working_dir: /Rustla2
    environment:
      GLOG_logtostderr: 1
    ports:
      - "3000"
    network_mode: host
