name: Backend build
on:
  push:
    paths:
      - '.github/workflows/backend.yml'
      - 'api/**'
      - '!api/.gitignore'
      - '!api/README.md'
      - '.gitmodules'
  pull_request:
    paths:
      - '.github/workflows/backend.yml'
      - 'api/**'
      - '!api/.gitignore'
      - '!api/README.md'
      - '.gitmodules'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
        
#     - name: Docker login
#       env:
#         username: ${{ github.actor }}
#         password: ${{ secrets.GITHUB_TOKEN }}
#       run: docker login https://docker.pkg.github.com -u ${username} -p ${password}
      
    - name: Build API image
      env:
        DOCKER_BUILDKIT: 1  
      run: cd ./api && docker build . -t docker.pkg.github.com/memelabs/rustla2/rustla2-api:latest
    - name: Download container structure test binary
      uses: fnkr/github-action-git-bash@v1
      with:
        args: "wget -O ./api/container-structure-test https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64"
     
    - name: Chmod
      uses: fnkr/github-action-git-bash@v1
      with:
        args: "chmod +x ./api/container-structure-test"
    
    - name: Test image
      uses: fnkr/github-action-git-bash@v1
      with:
        args: "./api/container-structure-test test --image docker.pkg.github.com/memelabs/rustla2/rustla2-api:latest --config ./api/container_test.yaml"

    - name: Push image
      uses: fnkr/github-action-git-bash@v1
      with:
        args: "./api/container-structure-test test --image docker.pkg.github.com/memelabs/rustla2/rustla2-api:latest --config ./api/container_test.yaml"

    - name: Docker login
      env:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      run: docker login https://docker.pkg.github.com -u ${username} -p ${password}
      
    - name: Docker push
      run: docker push docker.pkg.github.com/memelabs/rustla2/rustla2-api:latest


